### PR TITLE
add doi badge to readme

### PR DESCRIPTION
**Pull request by bvreede**
Badge code taken from https://zenodo.org/record/5654741.

### CODE REVIEW

**Review by Peter9192 — CHANGES_REQUESTED** [review]
When I preview the README on GitHub by selecting this branch, the badge doesn't render properly. Not sure why, but it seems to happen on other repo's as well. Could it be that the link to that badge is broken?

**Comment by Peter9192** [comment]
See https://github.com/zenodo/zenodo/issues/2165

**Comment by sverhoeven** [comment]
Link is same as on Zenodo page
zenodo org_record_5654741 (1)
Slow loading is not really something we can fix.

**Review by Peter9192 — APPROVED** [review]

**Comment by Peter9192** [comment]
> Slow loading is not really something we can fix.

It works now. Looks like Zenodo was having some problems this morning.

**Comment by bvreede** [comment]
Thanks @Peter9192 and @sverhoeven! Merged!

**Pull request merged**
