### PR TITLE
Polish notebooks and data 

### LINKED ISSUE #40: ASK constrained maps are not correct
Currently ASK constrained maps are not according to raw constrained data. In Atlas, those maps show the unconstrained values. This will be fixed in #38 .

### PR DESCRIPTION
**Pull request by SarahAlidoost**
closes #40 

Notebooks need raw data. The `AtlasData` dir available in EUCP sharepoint, has two folders: `raw` and `preprocess`. 
The previous data is archived in `AtlasData_v0.zip `and available in EUCP sharepoint, too.

The maps re-generated with these refactored codes in this branch are the same as the main branch, except for ASK to fix issue #40 and for UKCP because we got revised data.

### CODE REVIEW

**Comment by sverhoeven** [comment]
Was able to  create env with environment.yml, and documented it in https://github.com/eucp-project/atlas/blob/basic_docs/python/README.md#requirements as part of PR #43

**Comment by Peter9192** [comment]
Following @sverhoeven suggestion in #50, I enabled nbreview to aid in reviewing this PR: https://app.reviewnb.com/eucp-project/atlas/pull/38/

**Comment by Peter9192** [comment]
<p>Really nice work you've done here Sarah! Somehow some of the outputs don't render in reviewNB, but they are present locally. So the IPSL/Cordex notebook is now integrated into the IPSL/REA notebook, right? </p><p> </p><p>I took the liberty of pushing a commit that formats all the notebooks using black, hope that's okay. </p><p> </p>

**Comment by bvreede** [comment]
Data is on zenodo and has a DOI: 10.5281/zenodo.5645154

Markdown badge:
[DOI](https://doi.org/10.5281/zenodo.5645154)
`[DOI](https://doi.org/10.5281/zenodo.5645154)`

**Review by geek-yang — APPROVED** [review]
@SarahAlidoost Thanks for your awesome work! It even took me a while to review all the changes. That's a massive amount of work.

It is nice to see that now even the cordex files are preprocessed and grouped as independent files. This looks cleaner to the user and makes the whole workflow generic. Thanks again for the polishing. I think it is ready for merging.

**Comment by SarahAlidoost** [comment]
> Really nice work you've done here Sarah! Somehow some of the outputs don't render in reviewNB, but they are present locally. So the IPSL/Cordex notebook is now integrated into the IPSL/REA notebook, right?

Right, the notebook `maps_creator_IPSL_cordex` is now removed. Some codes are moved to the notebook `cleanup_IPSL_REA`. Now the maps of cordex can be created by the python script `maps_creator_atlas_data`.py.
> 
> I took the liberty of pushing a commit that formats all the notebooks using black, hope that's okay.

**Comment by SarahAlidoost** [comment]
> @SarahAlidoost Thanks for your awesome work! It even took me a while to review all the changes. That's a massive amount of work.
> 
> It is nice to see that now even the cordex files are preprocessed and grouped as independent files. This looks cleaner to the user and makes the whole workflow generic. Thanks again for the polishing. I think it is ready for merging.

Thanks for reviewing.

**Pull request merged**
